<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE shakemap-data [
<!ELEMENT shakemap-data (earthquake,stationlist)>
<!ELEMENT stationlist (station+)>
<!ATTLIST stationlist
  created	CDATA	#REQUIRED
>

<!ELEMENT station (comp+)>
<!ATTLIST station
  code		CDATA 			#REQUIRED
  name		CDATA 			#REQUIRED
  insttype	CDATA 			#REQUIRED
  lat		CDATA 			#REQUIRED
  lon		CDATA 			#REQUIRED
  source	(SCSN|CGS|NSMP) 	'SCSN'
  netid		CDATA			#REQUIRED
  commtype	(DIG|ANA) 		'DIG'
  dist          CDATA                   '10.0'
  loc		CDATA			''
>

<!ELEMENT comp (acc,vel,psa*)>
<!ATTLIST comp
  name          CDATA  #REQUIRED
  originalname  CDATA  #IMPLIED
>

<!ELEMENT acc EMPTY>
<!ELEMENT vel EMPTY>
<!ELEMENT psa03 EMPTY>
<!ELEMENT psa10 EMPTY>
<!ELEMENT psa30 EMPTY>
<!ATTLIST acc
  value  CDATA         #REQUIRED
  flag   CDATA        ''
>
<!ATTLIST vel
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa03
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa10
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa30
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ELEMENT  earthquake EMPTY>
<!ATTLIST earthquake
  id 		ID	#REQUIRED
  lat		CDATA	#REQUIRED
  lon		CDATA	#REQUIRED
  mag		CDATA	#REQUIRED
  year          CDATA   #REQUIRED
  month         CDATA   #REQUIRED
  day           CDATA   #REQUIRED
  hour          CDATA   #REQUIRED
  minute        CDATA   #REQUIRED
  second        CDATA   #REQUIRED
  timezone      CDATA   #REQUIRED
  depth		CDATA	#REQUIRED
  type		CDATA	#REQUIRED
  locstring	CDATA	#REQUIRED
  pga		CDATA   #REQUIRED
  pgv		CDATA   #REQUIRED
  sp03		CDATA   #REQUIRED
  sp10		CDATA   #REQUIRED
  sp30		CDATA   #REQUIRED
  created	CDATA	#REQUIRED
>
]>
<shakemap-data code_version="3.5" map_version="2">
<earthquake id="19940117123055" lat="34.21100" lon="-118.54600" mag="6.6" year="1994" month="1" day="17" hour="12" minute="30" second="55" timezone="GMT" depth="19" network="us" locstring="Northridge, California" created="1446237667" />
<stationlist created="1446237667">
<station code="CIIMOBS_1" name="3 (Intensity V)" insttype="Observed" lat="35.0271" lon="-120.5216" dist="188.755854" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="4.9">
<comp name="DERIVED">
<pga value="4.86" flag="0" />
<pgv value="5.34" flag="0" />
<psa03 value="9.45" flag="0" />
<psa10 value="7.78" flag="0" />
<psa30 value="1.71" flag="0" />
</comp>
</station>
<station code="CIIMOBS_2" name="3 (Intensity VI)" insttype="Observed" lat="34.5949" lon="-120.1199" dist="137.591261" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.7">
<comp name="DERIVED">
<pga value="8.73" flag="0" />
<pgv value="9.56" flag="0" />
<psa03 value="21.44" flag="0" />
<psa10 value="13.91" flag="0" />
<psa30 value="2.96" flag="0" />
</comp>
</station>
<station code="CIIMOBS_3" name="3 (Intensity V)" insttype="Observed" lat="34.4286" lon="-119.6379" dist="91.082406" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.3">
<comp name="DERIVED">
<pga value="7.62" flag="0" />
<pgv value="7.14" flag="0" />
<psa03 value="18.22" flag="0" />
<psa10 value="9.45" flag="0" />
<psa30 value="2.02" flag="0" />
</comp>
</station>
<station code="CIIMOBS_4" name="3 (Intensity VI)" insttype="Observed" lat="34.3954" lon="-119.5174" dist="79.851272" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="6.0">
<comp name="DERIVED">
<pga value="12.22" flag="0" />
<pgv value="11.89" flag="0" />
<psa03 value="27.41" flag="0" />
<psa10 value="16.11" flag="0" />
<psa30 value="3.36" flag="0" />
</comp>
</station>
<station code="CIIMOBS_5" name="3 (Intensity VII)" insttype="Observed" lat="34.1959" lon="-119.1559" dist="47.774915" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="7.1">
<comp name="DERIVED">
<pga value="27.92" flag="0" />
<pgv value="26.51" flag="0" />
<psa03 value="54.45" flag="0" />
<psa10 value="35.37" flag="0" />
<psa30 value="7.08" flag="0" />
</comp>
</station>
<station code="CIIMOBS_6" name="3 (Intensity VI)" insttype="Observed" lat="34.2291" lon="-119.0756" dist="40.840499" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="6.1">
<comp name="DERIVED">
<pga value="15.65" flag="0" />
<pgv value="12.79" flag="0" />
<psa03 value="31.94" flag="0" />
<psa10 value="15.57" flag="0" />
<psa30 value="3.20" flag="0" />
</comp>
</station>
<station code="CIIMOBS_7" name="3 (Intensity V)" insttype="Observed" lat="34.3289" lon="-119.0756" dist="41.194844" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.3">
<comp name="DERIVED">
<pga value="9.49" flag="0" />
<pgv value="7.14" flag="0" />
<psa03 value="20.44" flag="0" />
<psa10 value="8.26" flag="0" />
<psa30 value="1.74" flag="0" />
</comp>
</station>
<station code="CIIMOBS_8" name="3 (Intensity IV)" insttype="Observed" lat="35.3596" lon="-119.0756" dist="115.406613" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="3.7">
<comp name="DERIVED">
<pga value="1.59" flag="T" />
<pgv value="nan" flag="0" />
<psa03 value="nan" flag="0" />
<psa10 value="nan" flag="0" />
<psa30 value="nan" flag="0" />
</comp>
</station>
<station code="CIIMOBS_9" name="3 (Intensity VII)" insttype="Observed" lat="34.1959" lon="-118.9952" dist="35.242482" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="7.0">
<comp name="DERIVED">
<pga value="28.53" flag="0" />
<pgv value="24.65" flag="0" />
<psa03 value="53.82" flag="0" />
<psa10 value="31.03" flag="0" />
<psa30 value="6.19" flag="0" />
</comp>
</station>
<station code="CIIMOBS_10" name="3 (Intensity III)" insttype="Observed" lat="34.8609" lon="-120.4011" dist="171.240230" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="3.1">
<comp name="DERIVED">
<pga value="0.50" flag="0" />
<pgv value="nan" flag="0" />
<psa03 value="nan" flag="0" />
<psa10 value="nan" flag="0" />
<psa30 value="nan" flag="0" />
</comp>
</station>
<station code="CIIMOBS_11" name="3 (Intensity VII)" insttype="Observed" lat="34.2291" lon="-118.9551" dist="31.777335" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="6.8">
<comp name="DERIVED">
<pga value="25.92" flag="0" />
<pgv value="21.30" flag="0" />
<psa03 value="48.89" flag="0" />
<psa10 value="26.02" flag="0" />
<psa30 value="5.21" flag="0" />
</comp>
</station>
<station code="CIIMOBS_12" name="3 (Intensity VII)" insttype="Observed" lat="34.1626" lon="-118.8748" dist="28.562378" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="7.2">
<comp name="DERIVED">
<pga value="34.24" flag="0" />
<pgv value="28.51" flag="0" />
<psa03 value="62.02" flag="0" />
<psa10 value="35.10" flag="0" />
<psa30 value="6.93" flag="0" />
</comp>
</station>
<station code="CIIMOBS_13" name="3 (Intensity VII)" insttype="Observed" lat="34.1294" lon="-118.7944" dist="26.772167" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="7.1">
<comp name="DERIVED">
<pga value="32.76" flag="0" />
<pgv value="26.51" flag="0" />
<psa03 value="59.22" flag="0" />
<psa10 value="32.07" flag="0" />
<psa30 value="6.34" flag="0" />
</comp>
</station>
<station code="CIIMOBS_14" name="3 (Intensity VI)" insttype="Observed" lat="34.0296" lon="-118.7141" dist="30.603806" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="6.2">
<comp name="DERIVED">
<pga value="18.03" flag="0" />
<pgv value="13.76" flag="0" />
<psa03 value="35.21" flag="0" />
<psa10 value="16.05" flag="0" />
<psa30 value="3.27" flag="0" />
</comp>
</station>
<station code="CIIMOBS_15" name="3 (Intensity VIII)" insttype="Observed" lat="34.1626" lon="-118.7141" dist="22.258814" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="8.0">
<comp name="DERIVED">
<pga value="60.34" flag="0" />
<pgv value="51.08" flag="0" />
<psa03 value="100.33" flag="0" />
<psa10 value="63.52" flag="0" />
<psa30 value="12.19" flag="0" />
</comp>
</station>
<station code="CIIMOBS_16" name="3 (Intensity VI)" insttype="Observed" lat="34.0296" lon="-118.6739" dist="29.173274" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="6.1">
<comp name="DERIVED">
<pga value="17.17" flag="0" />
<pgv value="12.79" flag="0" />
<psa03 value="33.53" flag="0" />
<psa10 value="14.71" flag="0" />
<psa30 value="3.00" flag="0" />
</comp>
</station>
<station code="CIIMOBS_17" name="3 (Intensity VII)" insttype="Observed" lat="34.0961" lon="-118.6338" dist="23.766427" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="7.3">
<comp name="DERIVED">
<pga value="38.34" flag="0" />
<pgv value="30.67" flag="0" />
<psa03 value="67.33" flag="0" />
<psa10 value="36.84" flag="0" />
<psa30 value="7.23" flag="0" />
</comp>
</station>
<station code="CIIMOBS_18" name="3 (Intensity VI)" insttype="Observed" lat="35.1269" lon="-118.4731" dist="81.322284" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.6">
<comp name="DERIVED">
<pga value="9.48" flag="0" />
<pgv value="8.89" flag="0" />
<psa03 value="21.89" flag="0" />
<psa10 value="11.76" flag="0" />
<psa30 value="2.48" flag="0" />
</comp>
</station>
<station code="CIIMOBS_19" name="3 (Intensity VI)" insttype="Observed" lat="33.7636" lon="-118.4329" dist="50.678788" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="6.4">
<comp name="DERIVED">
<pga value="17.77" flag="0" />
<pgv value="15.92" flag="0" />
<psa03 value="36.58" flag="0" />
<psa10 value="20.49" flag="0" />
<psa30 value="4.19" flag="0" />
</comp>
</station>
<station code="CIIMOBS_20" name="3 (Intensity VIII)" insttype="Observed" lat="33.8966" lon="-118.4329" dist="37.988150" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="7.5">
<comp name="DERIVED">
<pga value="38.15" flag="0" />
<pgv value="35.48" flag="0" />
<psa03 value="70.31" flag="0" />
<psa10 value="46.74" flag="0" />
<psa30 value="9.20" flag="0" />
</comp>
</station>
<station code="CIIMOBS_21" name="3 (Intensity VII)" insttype="Observed" lat="34.4619" lon="-118.3927" dist="15.990906" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="6.7">
<comp name="DERIVED">
<pga value="29.44" flag="0" />
<pgv value="19.81" flag="0" />
<psa03 value="51.08" flag="0" />
<psa10 value="21.40" flag="0" />
<psa30 value="4.24" flag="0" />
</comp>
</station>
<station code="CIIMOBS_22" name="3 (Intensity V)" insttype="Observed" lat="33.7636" lon="-118.3526" dist="52.458529" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.3">
<comp name="DERIVED">
<pga value="8.88" flag="0" />
<pgv value="7.14" flag="0" />
<psa03 value="19.74" flag="0" />
<psa10 value="8.61" flag="0" />
<psa30 value="1.82" flag="0" />
</comp>
</station>
<station code="CIIMOBS_23" name="3 (Intensity VI)" insttype="Observed" lat="34.4951" lon="-118.2321" dist="26.930304" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="6.1">
<comp name="DERIVED">
<pga value="17.55" flag="0" />
<pgv value="12.79" flag="0" />
<psa03 value="33.92" flag="0" />
<psa10 value="14.51" flag="0" />
<psa30 value="2.95" flag="0" />
</comp>
</station>
<station code="CIIMOBS_24" name="3 (Intensity V)" insttype="Observed" lat="34.6281" lon="-118.1919" dist="40.898133" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.2">
<comp name="DERIVED">
<pga value="8.93" flag="0" />
<pgv value="6.64" flag="0" />
<psa03 value="19.36" flag="0" />
<psa10 value="7.62" flag="0" />
<psa30 value="1.61" flag="0" />
</comp>
</station>
<station code="CIIMOBS_25" name="3 (Intensity V)" insttype="Observed" lat="34.6946" lon="-118.1919" dist="47.099968" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.3">
<comp name="DERIVED">
<pga value="9.14" flag="0" />
<pgv value="7.14" flag="0" />
<psa03 value="20.05" flag="0" />
<psa10 value="8.45" flag="0" />
<psa30 value="1.78" flag="0" />
</comp>
</station>
<station code="CIIMOBS_26" name="3 (Intensity VI)" insttype="Observed" lat="33.7304" lon="-118.1116" dist="65.659089" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="6.0">
<comp name="DERIVED">
<pga value="12.90" flag="0" />
<pgv value="11.89" flag="0" />
<psa03 value="28.20" flag="0" />
<psa10 value="15.58" flag="0" />
<psa30 value="3.24" flag="0" />
</comp>
</station>
<station code="CIIMOBS_27" name="3 (Intensity VI)" insttype="Observed" lat="34.5284" lon="-118.0312" dist="43.219289" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.7">
<comp name="DERIVED">
<pga value="12.01" flag="0" />
<pgv value="9.56" flag="0" />
<psa03 value="25.36" flag="0" />
<psa10 value="11.44" flag="0" />
<psa30 value="2.38" flag="0" />
</comp>
</station>
<station code="CIIMOBS_28" name="3 (Intensity VI)" insttype="Observed" lat="33.9964" lon="-117.9911" dist="53.205144" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="6.0">
<comp name="DERIVED">
<pga value="13.67" flag="0" />
<pgv value="11.89" flag="0" />
<psa03 value="29.07" flag="0" />
<psa10 value="15.04" flag="0" />
<psa30 value="3.11" flag="0" />
</comp>
</station>
<station code="CIIMOBS_29" name="3 (Intensity V)" insttype="Observed" lat="34.5616" lon="-117.9509" dist="51.361286" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="4.7">
<comp name="DERIVED">
<pga value="6.15" flag="0" />
<pgv value="4.61" flag="0" />
<psa03 value="11.42" flag="0" />
<psa10 value="5.33" flag="0" />
<psa30 value="1.14" flag="0" />
</comp>
</station>
<station code="CIIMOBS_30" name="3 (Intensity V)" insttype="Observed" lat="33.6971" lon="-117.8706" dist="82.933352" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.0">
<comp name="DERIVED">
<pga value="6.49" flag="0" />
<pgv value="5.74" flag="0" />
<psa03 value="14.50" flag="0" />
<psa10 value="7.33" flag="0" />
<psa30 value="1.58" flag="0" />
</comp>
</station>
<station code="CIIMOBS_31" name="3 (Intensity VII)" insttype="Observed" lat="34.0296" lon="-117.8706" dist="59.995939" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="6.7">
<comp name="DERIVED">
<pga value="20.44" flag="0" />
<pgv value="19.81" flag="0" />
<psa03 value="42.17" flag="0" />
<psa10 value="26.75" flag="0" />
<psa30 value="5.44" flag="0" />
</comp>
</station>
<station code="CIIMOBS_32" name="3 (Intensity V)" insttype="Observed" lat="34.0629" lon="-117.8706" dist="58.124443" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.4">
<comp name="DERIVED">
<pga value="9.18" flag="0" />
<pgv value="7.68" flag="0" />
<psa03 value="20.56" flag="0" />
<psa10 value="9.48" flag="0" />
<psa30 value="2.00" flag="0" />
</comp>
</station>
<station code="CIIMOBS_33" name="3 (Intensity VI)" insttype="Observed" lat="34.1626" lon="-117.8706" dist="53.661958" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.8">
<comp name="DERIVED">
<pga value="12.04" flag="0" />
<pgv value="10.28" flag="0" />
<psa03 value="25.98" flag="0" />
<psa10 value="12.85" flag="0" />
<psa30 value="2.68" flag="0" />
</comp>
</station>
<station code="CIIMOBS_34" name="3 (Intensity V)" insttype="Observed" lat="33.8966" lon="-117.8304" dist="71.571108" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.3">
<comp name="DERIVED">
<pga value="8.15" flag="0" />
<pgv value="7.14" flag="0" />
<psa03 value="18.87" flag="0" />
<psa10 value="9.07" flag="0" />
<psa30 value="1.93" flag="0" />
</comp>
</station>
<station code="CIIMOBS_35" name="3 (Intensity VI)" insttype="Observed" lat="33.9964" lon="-117.8304" dist="65.090612" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.7">
<comp name="DERIVED">
<pga value="10.73" flag="0" />
<pgv value="9.56" flag="0" />
<psa03 value="23.90" flag="0" />
<psa10 value="12.26" flag="0" />
<psa30 value="2.57" flag="0" />
</comp>
</station>
<station code="CIIMOBS_36" name="3 (Intensity IV)" insttype="Observed" lat="33.5309" lon="-117.7903" dist="100.687188" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="4.4">
<comp name="DERIVED">
<pga value="4.24" flag="0" />
<pgv value="3.71" flag="0" />
<psa03 value="5.98" flag="0" />
<psa10 value="4.70" flag="0" />
<psa30 value="1.03" flag="0" />
</comp>
</station>
<station code="CIIMOBS_37" name="3 (Intensity VI)" insttype="Observed" lat="34.0961" lon="-117.7903" dist="63.167348" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="6.2">
<comp name="DERIVED">
<pga value="14.77" flag="0" />
<pgv value="13.76" flag="0" />
<psa03 value="31.70" flag="0" />
<psa10 value="18.15" flag="0" />
<psa30 value="3.75" flag="0" />
</comp>
</station>
<station code="CIIMOBS_38" name="3 (Intensity IV)" insttype="Observed" lat="33.5309" lon="-117.7501" dist="103.234274" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="4.3">
<comp name="DERIVED">
<pga value="3.95" flag="0" />
<pgv value="3.45" flag="0" />
<psa03 value="5.17" flag="0" />
<psa10 value="4.15" flag="0" />
<psa30 value="0.91" flag="0" />
</comp>
</station>
<station code="CIIMOBS_39" name="3 (Intensity V)" insttype="Observed" lat="33.7304" lon="-117.7501" dist="88.748629" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="4.9">
<comp name="DERIVED">
<pga value="5.99" flag="0" />
<pgv value="5.34" flag="0" />
<psa03 value="12.35" flag="0" />
<psa10 value="6.85" flag="0" />
<psa30 value="1.48" flag="0" />
</comp>
</station>
<station code="CIIMOBS_40" name="3 (Intensity VI)" insttype="Observed" lat="33.9964" lon="-117.7099" dist="74.629464" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.7">
<comp name="DERIVED">
<pga value="10.33" flag="0" />
<pgv value="9.56" flag="0" />
<psa03 value="23.43" flag="0" />
<psa10 value="12.55" flag="0" />
<psa30 value="2.64" flag="0" />
</comp>
</station>
<station code="CIIMOBS_41" name="3 (Intensity V)" insttype="Observed" lat="33.5974" lon="-117.6697" dist="103.750462" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="4.6">
<comp name="DERIVED">
<pga value="4.76" flag="0" />
<pgv value="4.29" flag="0" />
<psa03 value="7.77" flag="0" />
<psa10 value="5.54" flag="0" />
<psa30 value="1.21" flag="0" />
</comp>
</station>
<station code="CIIMOBS_42" name="3 (Intensity VI)" insttype="Observed" lat="33.9299" lon="-117.6697" dist="81.536032" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.9">
<comp name="DERIVED">
<pga value="11.42" flag="0" />
<pgv value="11.06" flag="0" />
<psa03 value="25.85" flag="0" />
<psa10 value="14.93" flag="0" />
<psa30 value="3.13" flag="0" />
</comp>
</station>
<station code="CIIMOBS_43" name="3 (Intensity VI)" insttype="Observed" lat="33.4644" lon="-117.6296" dist="116.144285" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.8">
<comp name="DERIVED">
<pga value="9.73" flag="0" />
<pgv value="10.28" flag="0" />
<psa03 value="23.23" flag="0" />
<psa10 value="14.64" flag="0" />
<psa30 value="3.10" flag="0" />
</comp>
</station>
<station code="CIIMOBS_44" name="3 (Intensity V)" insttype="Observed" lat="33.4976" lon="-117.6296" dist="113.674064" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="4.6">
<comp name="DERIVED">
<pga value="4.64" flag="0" />
<pgv value="4.29" flag="0" />
<psa03 value="7.52" flag="0" />
<psa10 value="5.63" flag="0" />
<psa30 value="1.23" flag="0" />
</comp>
</station>
<station code="CIIMOBS_45" name="3 (Intensity V)" insttype="Observed" lat="33.8634" lon="-117.6296" dist="88.669850" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.1">
<comp name="DERIVED">
<pga value="6.78" flag="0" />
<pgv value="6.17" flag="0" />
<psa03 value="16.23" flag="0" />
<psa10 value="8.02" flag="0" />
<psa30 value="1.72" flag="0" />
</comp>
</station>
<station code="CIIMOBS_46" name="3 (Intensity VI)" insttype="Observed" lat="33.8634" lon="-117.5894" dist="91.747319" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.8">
<comp name="DERIVED">
<pga value="10.39" flag="0" />
<pgv value="10.28" flag="0" />
<psa03 value="24.04" flag="0" />
<psa10 value="14.07" flag="0" />
<psa30 value="2.96" flag="0" />
</comp>
</station>
<station code="CIIMOBS_47" name="3 (Intensity VI)" insttype="Observed" lat="34.0961" lon="-117.5894" dist="80.519220" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.7">
<comp name="DERIVED">
<pga value="10.12" flag="0" />
<pgv value="9.56" flag="0" />
<psa03 value="23.17" flag="0" />
<psa10 value="12.71" flag="0" />
<psa30 value="2.68" flag="0" />
</comp>
</station>
<station code="CIIMOBS_48" name="3 (Intensity VI)" insttype="Observed" lat="33.9964" lon="-117.5091" dist="91.316080" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.6">
<comp name="DERIVED">
<pga value="9.18" flag="0" />
<pgv value="8.89" flag="0" />
<psa03 value="21.52" flag="0" />
<psa10 value="11.99" flag="0" />
<psa30 value="2.54" flag="0" />
</comp>
</station>
<station code="CIIMOBS_49" name="3 (Intensity V)" insttype="Observed" lat="34.0296" lon="-117.5091" dist="89.940757" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.2">
<comp name="DERIVED">
<pga value="7.19" flag="0" />
<pgv value="6.64" flag="0" />
<psa03 value="17.27" flag="0" />
<psa10 value="8.71" flag="0" />
<psa30 value="1.87" flag="0" />
</comp>
</station>
<station code="CIIMOBS_50" name="3 (Intensity IV)" insttype="Observed" lat="34.0629" lon="-117.4689" dist="92.210107" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="3.5">
<comp name="DERIVED">
<pga value="1.37" flag="T" />
<pgv value="nan" flag="0" />
<psa03 value="nan" flag="0" />
<psa10 value="nan" flag="0" />
<psa30 value="nan" flag="0" />
</comp>
</station>
<station code="CIIMOBS_51" name="3 (Intensity VI)" insttype="Observed" lat="33.9299" lon="-117.4287" dist="101.100315" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="6.0">
<comp name="DERIVED">
<pga value="11.45" flag="0" />
<pgv value="11.89" flag="0" />
<psa03 value="26.49" flag="0" />
<psa10 value="16.76" flag="0" />
<psa30 value="3.52" flag="0" />
</comp>
</station>
<station code="CIIMOBS_52" name="3 (Intensity V)" insttype="Observed" lat="33.9964" lon="-117.4287" dist="98.180649" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="4.8">
<comp name="DERIVED">
<pga value="5.47" flag="0" />
<pgv value="4.96" flag="0" />
<psa03 value="10.40" flag="0" />
<psa10 value="6.43" flag="0" />
<psa30 value="1.40" flag="0" />
</comp>
</station>
<station code="CIIMOBS_53" name="3 (Intensity V)" insttype="Observed" lat="34.5284" lon="-117.4287" dist="94.333926" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.0">
<comp name="DERIVED">
<pga value="6.27" flag="0" />
<pgv value="5.74" flag="0" />
<psa03 value="13.85" flag="0" />
<psa10 value="7.49" flag="0" />
<psa30 value="1.62" flag="0" />
</comp>
</station>
<station code="CIIMOBS_54" name="3 (Intensity V)" insttype="Observed" lat="33.9299" lon="-117.3886" dist="104.458851" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="4.6">
<comp name="DERIVED">
<pga value="4.75" flag="0" />
<pgv value="4.29" flag="0" />
<psa03 value="7.75" flag="0" />
<psa10 value="5.55" flag="0" />
<psa30 value="1.21" flag="0" />
</comp>
</station>
<station code="CIIMOBS_55" name="3 (Intensity V)" insttype="Observed" lat="33.1984" lon="-117.3083" dist="157.604980" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="4.9">
<comp name="DERIVED">
<pga value="5.11" flag="0" />
<pgv value="5.34" flag="0" />
<psa03 value="10.08" flag="0" />
<psa10 value="7.54" flag="0" />
<psa30 value="1.65" flag="0" />
</comp>
</station>
<station code="CIIMOBS_56" name="3 (Intensity IV)" insttype="Observed" lat="33.8634" lon="-117.3083" dist="114.317753" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="4.3">
<comp name="DERIVED">
<pga value="3.84" flag="0" />
<pgv value="3.45" flag="0" />
<psa03 value="4.99" flag="0" />
<psa10 value="4.29" flag="0" />
<psa30 value="0.96" flag="0" />
</comp>
</station>
<station code="CIIMOBS_57" name="3 (Intensity IV)" insttype="Observed" lat="33.9964" lon="-117.3083" dist="108.594745" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="4.2">
<comp name="DERIVED">
<pga value="3.47" flag="0" />
<pgv value="3.03" flag="0" />
<psa03 value="4.43" flag="0" />
<psa10 value="3.62" flag="0" />
<psa30 value="0.77" flag="0" />
</comp>
</station>
<station code="CIIMOBS_58" name="3 (Intensity III)" insttype="Observed" lat="32.9989" lon="-117.2681" dist="176.037203" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="3.3">
<comp name="DERIVED">
<pga value="0.66" flag="0" />
<pgv value="nan" flag="0" />
<psa03 value="nan" flag="0" />
<psa10 value="nan" flag="0" />
<psa30 value="nan" flag="0" />
</comp>
</station>
<station code="CIIMOBS_59" name="3 (Intensity IV)" insttype="Observed" lat="33.0654" lon="-117.2681" dist="170.631949" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="4.3">
<comp name="DERIVED">
<pga value="2.99" flag="0" />
<pgv value="3.45" flag="0" />
<psa03 value="4.33" flag="0" />
<psa10 value="4.75" flag="0" />
<psa30 value="1.06" flag="0" />
</comp>
</station>
<station code="CIIMOBS_60" name="3 (Intensity V)" insttype="Observed" lat="33.9631" lon="-117.2681" dist="113.338249" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.0">
<comp name="DERIVED">
<pga value="5.96" flag="0" />
<pgv value="5.74" flag="0" />
<psa03 value="12.98" flag="0" />
<psa10 value="7.72" flag="0" />
<psa30 value="1.67" flag="0" />
</comp>
</station>
<station code="CIIMOBS_61" name="3 (Intensity V)" insttype="Observed" lat="34.1626" lon="-117.2681" dist="107.620583" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.3">
<comp name="DERIVED">
<pga value="7.28" flag="0" />
<pgv value="7.14" flag="0" />
<psa03 value="17.79" flag="0" />
<psa10 value="9.72" flag="0" />
<psa30 value="2.08" flag="0" />
</comp>
</station>
<station code="CIIMOBS_62" name="3 (Intensity V)" insttype="Observed" lat="34.4619" lon="-117.2681" dist="107.340739" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.1">
<comp name="DERIVED">
<pga value="6.43" flag="0" />
<pgv value="6.17" flag="0" />
<psa03 value="15.16" flag="0" />
<psa10 value="8.29" flag="0" />
<psa30 value="1.79" flag="0" />
</comp>
</station>
<station code="CIIMOBS_63" name="3 (Intensity V)" insttype="Observed" lat="32.9656" lon="-117.2279" dist="181.250015" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.1">
<comp name="DERIVED">
<pga value="5.57" flag="0" />
<pgv value="6.17" flag="0" />
<psa03 value="12.59" flag="0" />
<psa10 value="9.05" flag="0" />
<psa30 value="1.97" flag="0" />
</comp>
</station>
<station code="CIIMOBS_64" name="3 (Intensity V)" insttype="Observed" lat="33.8301" lon="-117.2279" dist="122.614075" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.1">
<comp name="DERIVED">
<pga value="6.20" flag="0" />
<pgv value="6.17" flag="0" />
<psa03 value="14.47" flag="0" />
<psa10 value="8.47" flag="0" />
<psa30 value="1.83" flag="0" />
</comp>
</station>
<station code="CIIMOBS_65" name="3 (Intensity III)" insttype="Observed" lat="32.8659" lon="-117.1877" dist="191.985683" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="3.3">
<comp name="DERIVED">
<pga value="0.63" flag="0" />
<pgv value="nan" flag="0" />
<psa03 value="nan" flag="0" />
<psa10 value="nan" flag="0" />
<psa30 value="nan" flag="0" />
</comp>
</station>
<station code="CIIMOBS_66" name="3 (Intensity IV)" insttype="Observed" lat="33.1651" lon="-117.1476" dist="170.979524" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="4.2">
<comp name="DERIVED">
<pga value="2.58" flag="0" />
<pgv value="3.03" flag="0" />
<psa03 value="3.77" flag="0" />
<psa10 value="4.20" flag="0" />
<psa30 value="0.96" flag="0" />
</comp>
</station>
<station code="CIIMOBS_67" name="3 (Intensity III)" insttype="Observed" lat="33.1319" lon="-117.1074" dist="176.183665" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="3.4">
<comp name="DERIVED">
<pga value="0.77" flag="0" />
<pgv value="nan" flag="0" />
<psa03 value="nan" flag="0" />
<psa10 value="nan" flag="0" />
<psa30 value="nan" flag="0" />
</comp>
</station>
<station code="CIIMOBS_68" name="3 (Intensity V)" insttype="Observed" lat="33.4644" lon="-117.1074" dist="153.606288" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="5.3">
<comp name="DERIVED">
<pga value="6.60" flag="0" />
<pgv value="7.14" flag="0" />
<psa03 value="16.89" flag="0" />
<psa10 value="10.32" flag="0" />
<psa30 value="2.23" flag="0" />
</comp>
</station>
<station code="CIIMOBS_69" name="3 (Intensity V)" insttype="Observed" lat="32.7329" lon="-117.1074" dist="208.027881" source="DYFI Geocoded" netid="INTENSITY" commtype="Intensity" loc="" intensity="4.8">
<comp name="DERIVED">
<pga value="4.45" flag="0" />
<pgv value="4.96" flag="0" />
<psa03 value="7.97" flag="0" />
<psa10 value="7.30" flag="0" />
<psa30 value="1.61" flag="0" />
</comp>
</station>