<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE stationlist [
<!ELEMENT stationlist (station+)>
<!ATTLIST stationlist
  created	CDATA	#REQUIRED
>

<!ELEMENT station (comp+)>
<!ATTLIST station
  code		CDATA 			#REQUIRED
  name		CDATA 			#REQUIRED
  insttype	CDATA 			#REQUIRED
  lat		CDATA 			#REQUIRED
  lon		CDATA 			#REQUIRED
  source	(SCSN|CGS|NSMP) 	'SCSN'
  netid		CDATA			#REQUIRED
  commtype	(DIG|ANA) 		'DIG'
  dist          CDATA                   '10.0'
  loc		CDATA			''
  intensity     CDATA                   ''
>

<!ELEMENT comp (acc,vel,psa*)>
<!ATTLIST comp
  name          CDATA  #REQUIRED
  originalname  CDATA  #IMPLIED
>

<!ELEMENT acc EMPTY>
<!ELEMENT vel EMPTY>
<!ELEMENT psa03 EMPTY>
<!ELEMENT psa10 EMPTY>
<!ELEMENT psa30 EMPTY>
<!ATTLIST acc
  value  CDATA         #REQUIRED
  flag   CDATA        ''
>
<!ATTLIST vel
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa03
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa10
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa30
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
]>
<stationlist created="1270666393">
<station code="84117" name="ZIP Code 84117 Salt Lake City (Intensity I, 3 responses)" insttype="USGS (Did You Feel It?)" lat="40.6616275869" lon="-111.834691157" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="1.0">
<comp name="Intensity Questionnaire">
<acc value="0" />
<vel value="0" />
</comp>
</station>
<station code="85003" name="ZIP Code 85003 Phoenix (Intensity II, 21 responses)" insttype="USGS (Did You Feel It?)" lat="33.4508664262" lon="-112.078200656" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.3">
<comp name="Intensity Questionnaire">
<acc value="0.4" />
<vel value="0.3" />
</comp>
</station>
<station code="85004" name="ZIP Code 85004 Phoenix (Intensity III, 19 responses)" insttype="USGS (Did You Feel It?)" lat="33.4509709424" lon="-112.069437495" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.7">
<comp name="Intensity Questionnaire">
<acc value="0.6" />
<vel value="0.5" />
</comp>
</station>
<station code="85006" name="ZIP Code 85006 Phoenix (Intensity II, 7 responses)" insttype="USGS (Did You Feel It?)" lat="33.4658164689" lon="-112.04765751" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85007" name="ZIP Code 85007 Phoenix (Intensity II, 7 responses)" insttype="USGS (Did You Feel It?)" lat="33.4472639451" lon="-112.091442396" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85008" name="ZIP Code 85008 Phoenix (Intensity II, 28 responses)" insttype="USGS (Did You Feel It?)" lat="33.4647470616" lon="-111.987242627" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85009" name="ZIP Code 85009 Phoenix (Intensity II, 14 responses)" insttype="USGS (Did You Feel It?)" lat="33.4464762365" lon="-112.125393383" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85012" name="ZIP Code 85012 Phoenix (Intensity II, 24 responses)" insttype="USGS (Did You Feel It?)" lat="33.5092494746" lon="-112.069384535" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.1">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85013" name="ZIP Code 85013 Phoenix (Intensity II, 46 responses)" insttype="USGS (Did You Feel It?)" lat="33.5093154598" lon="-112.082487143" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.2">
<comp name="Intensity Questionnaire">
<acc value="0.4" />
<vel value="0.3" />
</comp>
</station>
<station code="85014" name="ZIP Code 85014 Phoenix (Intensity II, 34 responses)" insttype="USGS (Did You Feel It?)" lat="33.5091385401" lon="-112.056298008" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85015" name="ZIP Code 85015 Phoenix (Intensity II, 36 responses)" insttype="USGS (Did You Feel It?)" lat="33.5094276394" lon="-112.101978614" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85016" name="ZIP Code 85016 Phoenix (Intensity II, 69 responses)" insttype="USGS (Did You Feel It?)" lat="33.517430862" lon="-112.025656253" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85017" name="ZIP Code 85017 Phoenix (Intensity II, 19 responses)" insttype="USGS (Did You Feel It?)" lat="33.5096506291" lon="-112.123552455" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.4">
<comp name="Intensity Questionnaire">
<acc value="0.4" />
<vel value="0.3" />
</comp>
</station>
<station code="85018" name="ZIP Code 85018 Phoenix (Intensity II, 63 responses)" insttype="USGS (Did You Feel It?)" lat="33.4999043364" lon="-111.981694197" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.4">
<comp name="Intensity Questionnaire">
<acc value="0.4" />
<vel value="0.3" />
</comp>
</station>
<station code="85019" name="ZIP Code 85019 Phoenix (Intensity II, 11 responses)" insttype="USGS (Did You Feel It?)" lat="33.5094531735" lon="-112.142943207" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.2">
<comp name="Intensity Questionnaire">
<acc value="0.4" />
<vel value="0.3" />
</comp>
</station>
<station code="85020" name="ZIP Code 85020 Phoenix (Intensity II, 6 responses)" insttype="USGS (Did You Feel It?)" lat="33.567794768" lon="-112.052825319" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.3">
<comp name="Intensity Questionnaire">
<acc value="0.4" />
<vel value="0.3" />
</comp>
</station>
<station code="85021" name="ZIP Code 85021 Phoenix (Intensity II, 21 responses)" insttype="USGS (Did You Feel It?)" lat="33.560911944" lon="-112.094162426" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85022" name="ZIP Code 85022 Phoenix (Intensity II, 23 responses)" insttype="USGS (Did You Feel It?)" lat="33.6281007547" lon="-112.052224963" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85023" name="ZIP Code 85023 Phoenix (Intensity II, 13 responses)" insttype="USGS (Did You Feel It?)" lat="33.6318205289" lon="-112.094350385" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85024" name="ZIP Code 85024 Phoenix (Intensity II, 27 responses)" insttype="USGS (Did You Feel It?)" lat="33.6897535594" lon="-112.046136893" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85027" name="ZIP Code 85027 Phoenix (Intensity II, 82 responses)" insttype="USGS (Did You Feel It?)" lat="33.6780214103" lon="-112.10275322" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85028" name="ZIP Code 85028 Phoenix (Intensity II, 41 responses)" insttype="USGS (Did You Feel It?)" lat="33.5756539623" lon="-112.007520927" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85029" name="ZIP Code 85029 Phoenix (Intensity II, 32 responses)" insttype="USGS (Did You Feel It?)" lat="33.5955145814" lon="-112.110292046" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85031" name="ZIP Code 85031 Phoenix (Intensity II, 8 responses)" insttype="USGS (Did You Feel It?)" lat="33.4949949374" lon="-112.169008512" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85032" name="ZIP Code 85032 Phoenix (Intensity II, 79 responses)" insttype="USGS (Did You Feel It?)" lat="33.6258146965" lon="-112.004601341" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85033" name="ZIP Code 85033 Phoenix (Intensity III, 41 responses)" insttype="USGS (Did You Feel It?)" lat="33.4946719916" lon="-112.212047388" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.8">
<comp name="Intensity Questionnaire">
<acc value="0.7" />
<vel value="0.5" />
</comp>
</station>
<station code="85034" name="ZIP Code 85034 Phoenix (Intensity II, 12 responses)" insttype="USGS (Did You Feel It?)" lat="33.4356530994" lon="-112.01914906" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.5">
<comp name="Intensity Questionnaire">
<acc value="0.5" />
<vel value="0.4" />
</comp>
</station>
<station code="85035" name="ZIP Code 85035 Phoenix (Intensity II, 26 responses)" insttype="USGS (Did You Feel It?)" lat="33.4730616914" lon="-112.194727583" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.3">
<comp name="Intensity Questionnaire">
<acc value="0.4" />
<vel value="0.3" />
</comp>
</station>
<station code="85037" name="ZIP Code 85037 Phoenix (Intensity II, 70 responses)" insttype="USGS (Did You Feel It?)" lat="33.4910482559" lon="-112.267119647" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.5">
<comp name="Intensity Questionnaire">
<acc value="0.5" />
<vel value="0.4" />
</comp>
</station>
<station code="85040" name="ZIP Code 85040 Phoenix (Intensity II, 11 responses)" insttype="USGS (Did You Feel It?)" lat="33.4060802113" lon="-112.02560146" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85041" name="ZIP Code 85041 Phoenix (Intensity II, 17 responses)" insttype="USGS (Did You Feel It?)" lat="33.3850036889" lon="-112.105617345" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85042" name="ZIP Code 85042 Phoenix (Intensity II, 39 responses)" insttype="USGS (Did You Feel It?)" lat="33.3773663488" lon="-112.03548107" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85043" name="ZIP Code 85043 Phoenix (Intensity II, 39 responses)" insttype="USGS (Did You Feel It?)" lat="33.4302454705" lon="-112.193726063" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.1">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85044" name="ZIP Code 85044 Phoenix (Intensity II, 96 responses)" insttype="USGS (Did You Feel It?)" lat="33.3334596468" lon="-111.989390882" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85045" name="ZIP Code 85045 Phoenix (Intensity III, 5 responses)" insttype="USGS (Did You Feel It?)" lat="33.2995428884" lon="-112.106693061" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.8">
<comp name="Intensity Questionnaire">
<acc value="0.7" />
<vel value="0.5" />
</comp>
</station>
<station code="85048" name="ZIP Code 85048 Phoenix (Intensity II, 64 responses)" insttype="USGS (Did You Feel It?)" lat="33.3268912405" lon="-112.059331999" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85050" name="ZIP Code 85050 Phoenix (Intensity II, 52 responses)" insttype="USGS (Did You Feel It?)" lat="33.691005886" lon="-111.997417557" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85051" name="ZIP Code 85051 Phoenix (Intensity II, 19 responses)" insttype="USGS (Did You Feel It?)" lat="33.5595336106" lon="-112.133115469" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85053" name="ZIP Code 85053 Phoenix (Intensity II, 7 responses)" insttype="USGS (Did You Feel It?)" lat="33.630315151" lon="-112.131592313" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85054" name="ZIP Code 85054 Phoenix (Intensity II, 32 responses)" insttype="USGS (Did You Feel It?)" lat="33.682858412" lon="-111.94725431" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.4">
<comp name="Intensity Questionnaire">
<acc value="0.4" />
<vel value="0.3" />
</comp>
</station>
<station code="85083" name="ZIP Code 85083 Phoenix (Intensity II, 17 responses)" insttype="USGS (Did You Feel It?)" lat="33.7270058457" lon="-112.152522429" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85085" name="ZIP Code 85085 Phoenix (Intensity II, 16 responses)" insttype="USGS (Did You Feel It?)" lat="33.761817517" lon="-112.110971114" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85086" name="ZIP Code 85086 Phoenix (Intensity II, 6 responses)" insttype="USGS (Did You Feel It?)" lat="33.8392990805" lon="-112.107505027" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85087" name="ZIP Code 85087 New River (Intensity II, 3 responses)" insttype="USGS (Did You Feel It?)" lat="33.9292765496" lon="-112.145216867" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85201" name="ZIP Code 85201 Mesa (Intensity II, 27 responses)" insttype="USGS (Did You Feel It?)" lat="33.4360097578" lon="-111.849253223" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85202" name="ZIP Code 85202 Mesa (Intensity II, 49 responses)" insttype="USGS (Did You Feel It?)" lat="33.3845890227" lon="-111.873594991" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85203" name="ZIP Code 85203 Mesa (Intensity II, 15 responses)" insttype="USGS (Did You Feel It?)" lat="33.4529713191" lon="-111.804597794" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85204" name="ZIP Code 85204 Mesa (Intensity II, 25 responses)" insttype="USGS (Did You Feel It?)" lat="33.3972281258" lon="-111.787562228" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85205" name="ZIP Code 85205 Mesa (Intensity II, 14 responses)" insttype="USGS (Did You Feel It?)" lat="33.4336749811" lon="-111.718906636" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85206" name="ZIP Code 85206 Mesa (Intensity II, 25 responses)" insttype="USGS (Did You Feel It?)" lat="33.397247832" lon="-111.718407726" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85207" name="ZIP Code 85207 Mesa (Intensity II, 9 responses)" insttype="USGS (Did You Feel It?)" lat="33.4537025758" lon="-111.642258491" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85208" name="ZIP Code 85208 Mesa (Intensity II, 10 responses)" insttype="USGS (Did You Feel It?)" lat="33.4038263994" lon="-111.635185928" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85209" name="ZIP Code 85209 Mesa (Intensity II, 82 responses)" insttype="USGS (Did You Feel It?)" lat="33.378795044" lon="-111.634406037" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85210" name="ZIP Code 85210 Mesa (Intensity II, 34 responses)" insttype="USGS (Did You Feel It?)" lat="33.390066161" lon="-111.842629828" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85212" name="ZIP Code 85212 Mesa (Intensity II, 61 responses)" insttype="USGS (Did You Feel It?)" lat="33.3303959361" lon="-111.638413587" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85213" name="ZIP Code 85213 Mesa (Intensity II, 21 responses)" insttype="USGS (Did You Feel It?)" lat="33.4500535118" lon="-111.77019113" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85215" name="ZIP Code 85215 Mesa (Intensity II, 8 responses)" insttype="USGS (Did You Feel It?)" lat="33.5227693496" lon="-111.645975134" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85219" name="ZIP Code 85219 Apache Junction (Intensity II, 3 responses)" insttype="USGS (Did You Feel It?)" lat="33.4090649524" lon="-111.508962465" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85220" name="ZIP Code 85220 Apache Junction (Intensity II, 5 responses)" insttype="USGS (Did You Feel It?)" lat="33.4167214478" lon="-111.570899713" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85222" name="ZIP Code 85222 Casa Grande (Intensity II, 56 responses)" insttype="USGS (Did You Feel It?)" lat="32.9279682855" lon="-111.75853912" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.3">
<comp name="Intensity Questionnaire">
<acc value="0.4" />
<vel value="0.3" />
</comp>
</station>
<station code="85224" name="ZIP Code 85224 Chandler (Intensity II, 121 responses)" insttype="USGS (Did You Feel It?)" lat="33.3242923171" lon="-111.876421524" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85225" name="ZIP Code 85225 Chandler (Intensity II, 171 responses)" insttype="USGS (Did You Feel It?)" lat="33.3180532467" lon="-111.83194333" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85226" name="ZIP Code 85226 Chandler (Intensity II, 107 responses)" insttype="USGS (Did You Feel It?)" lat="33.2620583971" lon="-111.935348272" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85228" name="ZIP Code 85228 Coolidge (Intensity II, 18 responses)" insttype="USGS (Did You Feel It?)" lat="32.9464946797" lon="-111.516273281" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.5">
<comp name="Intensity Questionnaire">
<acc value="0.5" />
<vel value="0.4" />
</comp>
</station>
<station code="85231" name="ZIP Code 85231 Eloy (Intensity II, 4 responses)" insttype="USGS (Did You Feel It?)" lat="32.6628788745" lon="-111.557778454" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85233" name="ZIP Code 85233 Gilbert (Intensity II, 112 responses)" insttype="USGS (Did You Feel It?)" lat="33.3521613637" lon="-111.811120295" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85234" name="ZIP Code 85234 Gilbert (Intensity II, 65 responses)" insttype="USGS (Did You Feel It?)" lat="33.364618133" lon="-111.739305036" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85238" name="ZIP Code 85238 Maricopa (Intensity III, 20 responses)" insttype="USGS (Did You Feel It?)" lat="33.0203257655" lon="-111.949555525" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.9">
<comp name="Intensity Questionnaire">
<acc value="0.7" />
<vel value="0.6" />
</comp>
</station>
<station code="85239" name="ZIP Code 85239 Maricopa (Intensity III, 49 responses)" insttype="USGS (Did You Feel It?)" lat="32.9183486082" lon="-112.203695629" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.8">
<comp name="Intensity Questionnaire">
<acc value="0.7" />
<vel value="0.5" />
</comp>
</station>
<station code="85240" name="ZIP Code 85240 Queen Creek (Intensity II, 5 responses)" insttype="USGS (Did You Feel It?)" lat="33.2675550837" lon="-111.476924171" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85242" name="ZIP Code 85242 Queen Creek (Intensity II, 49 responses)" insttype="USGS (Did You Feel It?)" lat="33.2097683633" lon="-111.63348305" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85243" name="ZIP Code 85243 Queen Creek (Intensity II, 14 responses)" insttype="USGS (Did You Feel It?)" lat="33.1669448668" lon="-111.509548844" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85248" name="ZIP Code 85248 Chandler (Intensity II, 179 responses)" insttype="USGS (Did You Feel It?)" lat="33.2289555928" lon="-111.868219343" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.4">
<comp name="Intensity Questionnaire">
<acc value="0.4" />
<vel value="0.3" />
</comp>
</station>
<station code="85249" name="ZIP Code 85249 Chandler (Intensity II, 158 responses)" insttype="USGS (Did You Feel It?)" lat="33.2258691162" lon="-111.788307179" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.1">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85250" name="ZIP Code 85250 Scottsdale (Intensity II, 49 responses)" insttype="USGS (Did You Feel It?)" lat="33.5243507689" lon="-111.905771761" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85251" name="ZIP Code 85251 Scottsdale (Intensity II, 95 responses)" insttype="USGS (Did You Feel It?)" lat="33.4945613393" lon="-111.920929149" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.2">
<comp name="Intensity Questionnaire">
<acc value="0.4" />
<vel value="0.3" />
</comp>
</station>
<station code="85253" name="ZIP Code 85253 Paradise Valley (Intensity II, 31 responses)" insttype="USGS (Did You Feel It?)" lat="33.5454466839" lon="-111.959223874" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85254" name="ZIP Code 85254 Scottsdale (Intensity II, 220 responses)" insttype="USGS (Did You Feel It?)" lat="33.6150056383" lon="-111.952819658" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85255" name="ZIP Code 85255 Scottsdale (Intensity II, 28 responses)" insttype="USGS (Did You Feel It?)" lat="33.6766348456" lon="-111.812094046" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85257" name="ZIP Code 85257 Scottsdale (Intensity II, 21 responses)" insttype="USGS (Did You Feel It?)" lat="33.4646193151" lon="-111.91641945" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85258" name="ZIP Code 85258 Scottsdale (Intensity II, 98 responses)" insttype="USGS (Did You Feel It?)" lat="33.5647414965" lon="-111.897081669" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">
<acc value="0.3" />
<vel value="0.2" />
</comp>
</station>
<station code="85259" name="ZIP Code 85259 Scottsdale (Intensity II, 26 responses)" insttype="USGS (Did You Feel It?)" lat="33.5891822492" lon="-111.807914618" source="USGS (Did You Feel It?)" netid="CIIM" commtype="USGS (Did You Feel It?)" intensity="2.0">
<comp name="Intensity Questionnaire">